name: Jupyter Notebook Diff

on:
  pull_request:
    paths:
      - '**.ipynb'

jobs:
  jupyter-diff:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install nbdime
      run: pip install nbdime

    - name: Debug - Print Current Directory
      run: pwd

    - name: Debug - List Files in Directory
      run: ls -al


    - name: Generate Jupyter Notebook Diff
      run: nbdiff test1.ipynb ${{ GITHUB_BASE_REF }} --out=temp/diff.json
      env:
        GITHUB_BASE_REF: ${{ github.base_ref }}

    - name: Convert JSON Diff to HTML
      run: nbdiff-web temp/diff.json --out=temp/diff.html

    - name: Upload Jupyter Notebook HTML Diff
      uses: actions/upload-artifact@v2
      with:
        name: jupyter-diff
        path: temp/
