name: Jupyter Notebook Diff

on:
  pull_request:
    paths:
      - '**.ipynb'

jobs:
  jupyter-diff:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install nbdime and nbconvert
      run: pip install nbdime nbconvert

    - name: Generate Jupyter Notebook Diff
      run: |
        nbdiff-web ${GITHUB_BASE_REF} ${GITHUB_HEAD_REF} --out temp/diff.html
        jupyter nbconvert --to html --output-dir=temp/ temp/*.ipynb
      env:
        GITHUB_BASE_REF: ${{ github.base_ref }}
        GITHUB_HEAD_REF: ${{ github.head_ref }}

    - name: Upload Jupyter Notebook HTML Diff
      uses: actions/upload-artifact@v2
      with:
        name: jupyter-diff
        path: temp/
