name: Diff Jupyter Notebooks and Create GitHub Pages Site

on:
  pull_request:
    types: [opened]

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install nbdiff-web
        run: conda install -c conda-forge nbdiff-web

      - name: Diff notebooks
        run: nbdiff-web .

  comment:
    runs-on: ubuntu-latest
    needs: diff
    steps:
      - uses: actions/github-script@v2
        with:
          script: |
            const github = require('@actions/github');
            const { pull_request } = github.context;
            const url = `https://${pull_request.head.repo.AyushiPanth}.github.io/diff.html`;
            github.issues.comment({
              issue_number: pull_request.number,
              body: `The diff of the Jupyter notebooks can be found here: ${url}`,
            });
