name: Jupyter Notebook Diff

on:
  pull_request:
    paths:
      - '**.ipynb'

jobs:
  jupyter-diff:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install nbdime
      run: pip install nbdime

    - name: Generate Jupyter Notebook Diff
      run: nbdiff-web ${{ github.base_ref }} ${{ github.head_ref }}
