name: Generate GitHub Page for Diff

on:
  pull_request:
    types: [opened, edited]

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install nbdime
        run: pip install nbdime
      - name: Diff notebooks
        uses: jupyter/nbdime-action@v1.0.0
        with:
          files: '**/*.ipynb'
          output-format: 'html'
          output-path: 'diff.html'

  deploy:
    runs-on: ubuntu-latest
    needs: diff
    steps:
      - uses: actions/github-pages@v2
          with:
            page_name: diff
            branch: gh-pages
            source_directory: diff.html
