name: Pull Request Workflow

on:
  pull_request:
    types:
      - opened  # Trigger the workflow when a pull request is opened

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
    - name: nbdime-git-diff
      uses: raybellwaves/nbdime-git-diff@0.0.6
      with:
        some_input: some_value
