name: Jupyter Notebook Diff

on:
  pull_request:
    paths:
      - 'test1.ipynb'

jobs:
  jupyter-diff:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install nbdime
      run: pip install nbdime

    - name: Create temp directory
      run: mkdir -p temp

    - name: Copy Jupyter Notebook to temp directory
      run: cp test1.ipynb temp/test1.ipynb

    - name: Generate Jupyter Notebook Diff
      run: nbdiff temp/test1.ipynb temp/test1.ipynb --out=temp/diff.json

    - name: Convert JSON Diff to HTML
      run: nbdiff-web temp/diff.json --out=temp/diff.html

    - name: Move HTML Diff to workspace
      run: mv temp/diff.html $GITHUB_WORKSPACE/diff.html

    - name: Upload Jupyter Notebook HTML Diff
      uses: actions/upload-artifact@v2
      with:
        name: jupyter-diff
        path: $GITHUB_WORKSPACE/diff.html
