name: Diff Jupyter Notebooks and Create GitHub Pages Site

on:
  pull_request:
    types: [opened]

jobs:
  generate-diff-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install nbdime and ipython_genutils
        run: |
          pip install nbdime ipython_genutils
        shell: bash

      - name: Configure nbdime for Git
        run: |
          nbdime config-git --enable --global
        shell: bash

      - name: Generate HTML view of Git diff
        run: |
          nbdiff-web HEAD^ HEAD -o diff.html
        shell: bash

      - name: Upload HTML view as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: nbdime-diff-html
          path: diff.html
