name: Diff Jupyter Notebooks and Create GitHub Pages Site

on:
  pull_request:
    types: [opened]

jobs:
  diff:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{github.workspace}} # Set the working directory for the entire job
    
    steps:

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - uses: actions/checkout@v2

      - name: Install nbconvert
        run: pip install nbconvert

      - name: Install @actions/github module
        run: npm install -g @actions/github

      - name: Set up Git user identity
        run: |
          git config --global user.email "lit2019073@iiitl.ac.in"
          git config --global user.name "Ayushi Panth"
      - name: Diff notebooks
        run: |
          # Get the hash of the head commit of the pull request.
          head_commit=$(git rev-parse HEAD)
      
          # Get the changed files in the pull request.
          changed_files=$(git diff --name-only $head_commit HEAD --)
      
          # Loop through the changed files.
          for file in $changed_files; do
            # Generate the path for the diff.html file.
            diff_file_path=$(dirname $file)/diff.html
            nbdiff $file $file -o $diff_file_path
          done

          # Separate step to print the paths
      - name: Print paths of generated diff.html files
        run: |
          # Get the hash of the head commit of the pull request.
          head_commit=$(git rev-parse HEAD)
          
          # Get the changed files in the pull request.
          changed_files=$(git diff --name-only $head_commit HEAD --)
          
          # Loop through the changed files and print the paths.
          for file in $changed_files; do
          # Generate the path for the diff.html file.
            diff_file_path=$(dirname $file)/diff.html
            echo "Generated $diff_file_path"
          done          

          
      - name: Install GitHub CLI (gh)
        run: |
          curl -sSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg arch=all] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt-get update
          sudo apt-get install gh

      - name: Create Comment
        run: |
          # Replace with the correct URL to your diff file
          diff_url="https://ayushipanth.github.io/test1/path/to/diff.html"
          gh issue comment ${{ github.event.pull_request.number }} -b "The diff of the Jupyter notebooks can be found here: $diff_url"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
